' Copyright (c) 2019-2025 Thomas Hugo Williams
' License MIT <https://opensource.org/licenses/MIT>
' For MMBasic 6.00

' Constant values to inline

'!define INLINE_CONSTANTS

' From "console.inc"
'!replace S_WRITE   &b01
'!replace S_READ    &b10

' From "execute.inc"
'!replace E_OK             0
'!replace E_UNKNOWN        1
'!replace E_UNIMPLEMENTED  2
'!replace E_BREAK          3
'!replace E_QUIT           4
'!replace E_DEBUG          5
'!replace E_REPEAT         6

' From "main.bas"
'!replace INSTALL_DIR    0
'!replace RESOURCES_DIR  1
'!replace SAVE_DIR       2
'!replace SCRIPT_DIR     3
'!replace STORY_DIR      4
'!replace STORY_FILE     5

' From "objects.inc"
'!replace PARENT   4
'!replace SIBLING  5
'!replace CHILD    6
