' Copyright (c) 2020-2023 Thomas Hugo Williams
'
' Optimised CMM1 version of Z-MIM

'!comments     off
'!empty-lines  single
'!indent       0
'!spacing      minimal
'!define       TARGET_CMM1
'!define       NO_DEBUG
'!replace      "mem_cmm2_safe.inc"  "mem_cmm1.inc"
'!replace      "\title.txt"         "\titl_cm1.txt"
'!replace      "\credits.txt"       "\cred_cm1.txt"
'!replace      C_HEIGHT             36
'!replace      C_WIDTH              80

#Include "constants.mbt"
#Include "ids.mbt"
#Include "main.bas"
