' Copyright (c) 2019-2025 Thomas Hugo Williams
' License MIT <https://opensource.org/licenses/MIT>
' For MMBasic 6.00

' Optimised CMM2 version of Z-MIM

'!comments     off
'!empty-lines  single
'!indent       1
'!spacing      minimal
'!define       TARGET_CMM2
'!define       NO_DEBUG
'!replace      "mem_cmm2_safe.inc"  "mem_cmm2_fast.inc"

#Include "constants.mbt"
#Include "ids.mbt"
#Include "main.bas"
